import { DiagramContainer, Metric, type SlideDefinition } from "./primitives";
import { AuthorityGateDiagram, BusinessRoadmapDiagram, ExperienceGraph, ExperienceLoopDiagram, MarketFunnelDiagram, SystemFlowDiagram, WorkshopValueDiagram } from "./diagrams";
const architectureNote="Architecture supplied by ORVECT · newer than the local checkout; deployment not verified here.";
const marketUrl="https://www.figiefa.eu/en/publications/european-independent-automotive-aftermarket-panorama.html";
function List({items}:{items:string[]}){return <ul className="deck-list">{items.map(item=><li key={item}>{item}</li>)}</ul>}
export const investorSlides:SlideDefinition[]=[
{id:"cover",section:"Investor presentation / September 2026",title:"Beyond the fault code.",cover:true,body:<><p className="cover-subtitle">Diagnostic intelligence for independent workshops.</p><div className="cover-signal" aria-hidden="true"><svg viewBox="0 0 1200 220"><path d="M0 150H300L360 90H520L580 150H760L820 35H940L1000 150H1200"/><circle cx="820" cy="35" r="9"/></svg><span>CONTEXT → EVIDENCE → CONTROL → LEARNING</span></div></>},
{id:"problem",section:"01 / The problem",title:"A fault code tells you where to look. It does not tell you what failed.",body:<div className="problem-columns"><div><span className="problem-symbol">≠</span><h2>Fault code ≠ root cause</h2><p>A signal is not a diagnosis.</p></div><div><span className="problem-symbol">⋯</span><h2>Knowledge is fragmented</h2><p>Across tools, sources and people.</p></div><div><span className="problem-symbol">↗</span><h2>Test order costs time</h2><p>The next check matters.</p></div></div>},
{id:"product",section:"02 / The product",title:"A workshop case becomes a controlled diagnostic path.",body:<div className="product-flow"><div><h2>Technician</h2><List items={["Vehicle + DTCs","Symptoms","Measurements + photos"]}/></div><div className="product-core"><span>→</span><strong>ORVECT</strong><small>Context. Evidence. Control.</small><span>→</span></div><div><h2>Useful output</h2><List items={["Ranked hypotheses","Evidence for / against","Next useful check","Safety status + traceable report"]}/></div></div>},
{id:"workspace",section:"03 / The technician’s workspace",title:"Evidence first. A useful next check.",body:<div className="product-mock"><div className="mock-header"><strong>VW Golf VII <span> / 1.4 TSI</span></strong><b>P0301</b><span>ILLUSTRATIVE CASE</span></div><div className="mock-grid"><div><h2>Ranked hypotheses</h2>{["Injector cylinder 1","Ignition coil","Compression issue"].map((s,i)=><div className={`hypothesis ${i===0?"selected":""}`} key={s}><span>0{i+1}</span>{s}<small>Unconfirmed</small></div>)}</div><div><h2>Evidence for / against</h2><p><b>For</b> · Cylinder 1 misfire reported.</p><p><b>Against certainty</b> · No injector measurement. Ignition and compression remain open.</p><div className="next-check"><small>CURRENT RECOMMENDED CHECK</small><strong>Review ignition test results before isolating the injector.</strong></div></div></div><div className="mock-status">Safety: professional assessment required <span>Traceable report →</span></div></div>,footer:"Synthetic interface example; ranking and check are illustrative, not a validated diagnosis or repair instruction."},
{id:"system",section:"04 / How it works",title:"Nebius reasons. Tavily searches. ORVECT controls authority.",body:<DiagramContainer><SystemFlowDiagram/></DiagramContainer>,footer:architectureNote},
{id:"authority",section:"05 / Controlled authority",title:"The model never gets unconditional authority.",body:<><DiagramContainer><AuthorityGateDiagram/></DiagramContainer><div className="boundary"><b>The LLM cannot</b><span>Invent canonical sources</span><span>Rewrite DTC definitions</span><span>Decide safety</span><span>Turn field evidence into OEM truth</span></div></>,footer:"Backend owns provenance, canonical DTC integrity and safety decisions. Controls do not establish diagnostic accuracy."},
{id:"experience",section:"06 / The Experience Engine",title:"Learn from validated outcomes. Never blind self-training.",body:<div className="two-col experience-layout"><ExperienceLoopDiagram/><div><h2>Admission rules</h2><List items={["Known outcome + canonical cause","Sufficient quality + consent","2+ independent workshops for cross-garage reuse","Confirmations > contradictions"]}/><p className="key-line">Field evidence never becomes OEM truth.</p></div></div>,footer:architectureNote},
{id:"moat",section:"07 / Proprietary value",title:"The model is not the moat. Validated diagnostic experience is.",body:<div className="two-col moat-layout"><div><p className="section-label">REPLACEABLE LAYERS</p><List items={["Nebius → replaceable","Tavily → replaceable","Cloud infrastructure → replaceable","UI technology → replaceable"]}/></div><ExperienceGraph/></div>,footer:"Proprietary-value thesis: compatible, consented and corroborated workshop outcomes. Network value remains to be validated."},
{id:"proof",section:"08 / Current proof",title:"An engineering foundation. The workshop proof starts now.",body:<><div className="metrics"><Metric value="3" label="garages under beta agreements"/><Metric value="262" label="backend tests passed · 1 skipped"/><Metric value="1" label="main Nebius reasoning call / diagnostic"/></div><p className="proof-support">Reported implemented: Experience Engine · adaptive next checks · cross-garage aggregation · canonical multilingual cause normalization.</p><p className="muted">11,881 tokens measured on one test diagnostic. A single observation, not an average.</p></>,footer:"ORVECT-supplied status, September 2026. Historical test count and newer architecture are not verified by this checkout. No paying-customer or accuracy claim."},
{id:"value",section:"09 / Workshop value",title:"Less searching. Better test order. Knowledge that stays.",body:<><WorkshopValueDiagram/><div className="two-col"><div><h2>Aim to reduce</h2><p>Unnecessary checks, information searching and dead-end diagnostic paths.</p></div><div><h2>Aim to improve</h2><p>Consistency, traceability and knowledge reuse.</p></div></div><p className="assumption">Illustrative only: 10 minutes × €60/hour = €10 of technician opportunity cost. Time savings have not yet been measured.</p></>},
{id:"plan",section:"10 / Business plan",title:"Earn the right to scale, one proof at a time.",body:<><BusinessRoadmapDiagram/><div className="three-col roadmap-notes"><p><b>Product proof</b><br/>Collect outcomes. Validate usefulness.</p><p><b>Business proof</b><br/>Pricing interviews, conversion signals and experience density.</p><p><b>Scale proof</b><br/>Repeatable distribution through workshop networks and partnerships.</p></div></>,footer:"All future garage counts are targets, not forecasts or signed commitments. Timing is relative to plan launch."},
{id:"market",section:"11 / Market opportunity",title:"A large installed base. A focused entry point.",body:<div className="two-col market-layout"><div><MarketFunnelDiagram/><p className="muted">~195M EU vehicles older than 4 years<br/>~€73B independent parts market context</p></div><div><p className="section-label">INTERNAL BOTTOM-UP SOFTWARE SCENARIO</p><p className="formula">250,000 outlets × €79 × 12</p><Metric value="€237M" label="illustrative annual software TAM"/><p className="key-line">1% = 2,500 workshops ≈ €2.37M ARR</p><p className="muted">ORVECT pricing scenario, not a FIGIEFA software-market estimate. Not all outlets are qualified buyers; wedge size remains to be validated.</p></div></div>,footer:<><a href={marketUrl} target="_blank" rel="noreferrer">FIGIEFA / Roland Berger · European Independent Automotive Aftermarket Panorama (2024), pp. 2, 13</a> · ~250,000 EU IAM service outlets (2023). Funnel is conceptual.</>},
{id:"pricing",section:"12 / Business model",title:"A predictable workshop bill. Room to grow with usage.",body:<><p className="section-label">WORKING PRICING HYPOTHESIS · NOT YET VALIDATED</p><div className="pricing">{[["Pilot","€0","Structured beta"],["Workshop","€79","/ month · 100 diagnostics"],["Pro","€149","/ month · 300 diagnostics"],["Network","Custom","Network agreement"]].map(([name,price,detail])=><div key={name}><h2>{name}</h2><strong>{price}</strong><p>{detail}</p></div>)}</div><p className="proof-support">Recurring revenue · predictable bills · high gross-margin potential · expansion with usage</p></>,footer:"Included volumes and pricing are hypotheses. Overage policy, willingness to pay and realized margins remain to be validated."},
{id:"economics",section:"13 / Business economics",title:"Low inference cost is only one part of the business.",body:<div className="two-col"><div><h2>Variable cost</h2><p className="key-line">Model inference: currently reported very low.</p><p>Tavily may be the larger AI-search cost when triggered.</p><p className="muted">Working assumption. Instrument complete cases, retries and research frequency.</p></div><div><h2>Core operating costs</h2><List items={["Engineering + infrastructure","Technical data / licensing","Legal, compliance + security","Workshop onboarding","Sales + workshop success"]}/></div></div>,footer:"Cost observations supplied by ORVECT. Full cost per case, gross margin, CAC, retention and payback are not yet validated."},
{id:"round",section:"14 / The pre-seed round",title:"$350k to turn product proof into business proof.",body:<><div className="round-grid"><div><Metric value="$4.5M" label="working pre-money valuation"/><p className="key-line">~7.2% illustrative dilution</p><p className="muted">$350k ÷ ($4.5M + $350k), before option-pool changes or other instruments.</p><p className="valuation-note">The $4.5M valuation is ORVECT’s working fundraising position. It is not a third-party certified valuation.</p></div><div><h2>Proposed use of funds</h2><div className="allocation-bar" aria-hidden="true">{[35,30,15,10,10].map((n,i)=><span key={i} style={{flex:n,opacity:1-i*.14}}/>)}</div><ul className="allocation">{[[35,"Product + data"],[30,"GTM / workshop success"],[15,"Legal / data / compliance"],[10,"Infrastructure / security"],[10,"Reserve"]].map(([n,s])=><li key={s}><strong>{n}%</strong>{s}</li>)}</ul></div></div><p className="benchmark">Valuation context: Europe pre-seed ~$3.3M · Sweden Scorecard parameter ~50.38M SEK. Different samples and methods; neither certifies ORVECT’s valuation.</p></>,footer:<><a href="https://www.equidam.com/startup-valuation-delta-h1-2026/" target="_blank" rel="noreferrer">Equidam · Startup Valuation Delta H1 2026</a> · <a href="https://www.equidam.com/parameters-update-p6-3-average-and-maximum-valuations/" target="_blank" rel="noreferrer">Sweden Scorecard parameters · July 2026</a></>},
{id:"closing",section:"ORVECT / Context. Evidence. Control. Learning.",title:"Beyond the fault code.",cover:true,body:<><p className="closing-lead">3 pilot garages today.<br/><span>A growing diagnostic evidence network tomorrow.</span></p><p className="closing-copy">The goal is not to build another AI wrapper.<br/>It is diagnostic intelligence that becomes more useful with every validated workshop outcome.</p></>,footer:"Pilot status supplied by ORVECT · network growth is an ambition, not a forecast."},
];
