import { BrandSignature, DiagramContainer, Metric, type SlideDefinition } from "./primitives";
import { AuthorityGateDiagram, BusinessRoadmapDiagram, ExperienceGraph, ExperienceLoopDiagram, MarketFunnelDiagram, SystemFlowDiagram } from "./diagrams";
const marketUrl="https://www.figiefa.eu/en/publications/european-independent-automotive-aftermarket-panorama.html";
function List({items}:{items:string[]}){return <ul className="deck-list">{items.map(item=><li key={item}>{item}</li>)}</ul>}
export const investorSlides:SlideDefinition[]=[
{id:"cover",section:"Investor presentation / September 2026",title:"Beyond the fault code.",cover:true,body:<><p className="cover-subtitle">A clearer next check. A stronger workshop memory.</p><div className="cover-signal" aria-hidden="true"><svg viewBox="0 0 1200 220"><path d="M0 150H300L360 90H520L580 150H760L820 35H940L1000 150H1200"/><circle cx="820" cy="35" r="9"/></svg><span>DIAGNOSTIC INTELLIGENCE / INDEPENDENT WORKSHOPS</span></div></>},
{id:"problem",section:"01 / The problem",title:"The code is only the beginning",body:<div className="problem-columns"><div><span className="problem-symbol">≠</span><h2>A symptom, not a cause</h2><p>A signal is not a diagnosis.</p></div><div><span className="problem-symbol">⋯</span><h2>Knowledge is fragmented</h2><p>Across tools, sources and people.</p></div><div><span className="problem-symbol">↗</span><h2>Every check takes time</h2><p>The next check matters.</p></div></div>},
{id:"workspace",section:"02 / The product",title:"The next check, with the evidence behind it",body:<div className="product-mock"><div className="mock-header"><strong>VW Golf VII <span> / 1.4 TSI</span></strong><b>P0301</b><span>ILLUSTRATIVE CASE</span></div><div className="mock-grid"><div><h2>Ranked hypotheses</h2>{["Injector cylinder 1","Ignition coil","Compression issue"].map((s,i)=><div className={`hypothesis ${i===0?"selected":""}`} key={s}><span>0{i+1}</span>{s}<small>Unconfirmed</small></div>)}</div><div><h2>Evidence for / against</h2><p><b>For</b> · Cylinder 1 misfire reported.</p><p><b>Against certainty</b> · No injector measurement. Ignition and compression remain open.</p><div className="next-check"><small>CURRENT RECOMMENDED CHECK</small><strong>Review ignition test results before isolating the injector.</strong></div></div></div><div className="mock-status">Safety: professional assessment required <span>Traceable report →</span></div></div>,footer:"Illustrative interface. Hypotheses and checks require professional validation."},
{id:"proof",section:"03 / Early evidence",title:"3 garages. 12 diagnostics. A concrete starting point.",body:<><div className="traction-pair"><Metric value="3" label="garages under beta agreements"/><Metric value="12" label="diagnostics reported to date"/></div><div className="evidence-next"><span className="section-label">NEXT TO MEASURE</span><p>Time to the next useful check, confirmed outcomes and repeat workshop use.</p></div></>,footer:"September 2026. Early activity figures, not evidence of diagnostic accuracy or paying customers."},
{id:"value",section:"04 / Workshop value",title:"Less searching. More structured diagnosis.",body:<div className="value-rows"><div><span>01</span><h2>One case, one context</h2><p>Vehicle details, fault codes and workshop observations stay together.</p></div><div><span>02</span><h2>A reason for each check</h2><p>Hypotheses connect to supporting evidence and what remains unknown.</p></div><div><span>03</span><h2>Experience the team can reuse</h2><p>Confirmed outcomes can inform future compatible cases.</p></div></div>,footer:"Product value proposition. Time savings and workshop impact remain to be measured."},
{id:"moat",section:"05 / The Experience Engine",title:"Workshop experience can compound",body:<div className="experience-story"><div className="experience-statement"><span className="section-label">ORVECT’S PROPRIETARY VALUE</span><p>Each validated outcome can make the next compatible case more useful.</p></div><div className="experience-rules"><h2>Quality before reuse</h2><List items={["A known outcome and confirmed cause","Consent and sufficient evidence","Independent workshop corroboration"]}/><p className="key-line">ORVECT controls what enters the shared knowledge.</p></div></div>,footer:"Proprietary-value thesis. Network benefits remain to be validated. Field evidence stays distinct from OEM documentation."},
{id:"market",section:"06 / Market opportunity",title:"Independent workshops, European potential",body:<div className="two-col market-layout"><div><MarketFunnelDiagram/><p className="muted">Initial focus: independent workshops<br/>with complex multi-brand diagnostics</p></div><div><p className="section-label">INTERNAL BOTTOM-UP SOFTWARE SCENARIO</p><p className="formula">250,000 outlets × €79 × 12</p><Metric value="€237M" label="illustrative annual software TAM"/><p className="key-line">1% = 2,500 workshops ≈ €2.37M ARR</p><p className="muted">Illustrative scenario. Qualified buyers and initial addressable segment remain to be validated.</p></div></div>,footer:<><a href={marketUrl} target="_blank" rel="noreferrer">FIGIEFA / Roland Berger · European Independent Automotive Aftermarket Panorama (2024), pp. 2, 13</a> · ~250,000 EU IAM service outlets (2023). Funnel is conceptual.</>},
{id:"pricing",section:"07 / Business model",title:"A monthly subscription per workshop",body:<><p className="section-label">WORKING PRICING HYPOTHESIS · NOT YET VALIDATED</p><div className="pricing">{[["Pilot","€0","Structured beta"],["Workshop","€79","/ month · 100 diagnostics"],["Pro","€149","/ month · 300 diagnostics"],["Network","Custom","Network agreement"]].map(([name,price,detail])=><div key={name}><h2>{name}</h2><strong>{price}</strong><p>{detail}</p></div>)}</div><p className="proof-support">Free beta to establish value. Paid plans to test willingness to pay.</p></>,footer:"Pricing and volumes are hypotheses. Willingness to pay, overages and realized margins remain to be validated."},
{id:"plan",section:"08 / Route to market",title:"Pilot evidence comes before network expansion",body:<><BusinessRoadmapDiagram/><div className="three-col roadmap-notes"><p><b>Product proof</b><br/>Collect outcomes. Validate usefulness.</p><p><b>Business proof</b><br/>Pricing interviews, conversion signals and experience density.</p><p><b>Scale proof</b><br/>Repeatable distribution through workshop networks and partnerships.</p></div></>,footer:"All future garage counts are targets, not forecasts or signed commitments. Timing is relative to plan launch."},
{id:"team",section:"09 / Co-founders & execution",title:"Building around the workshop",body:<><div className="cofounders"><div><span className="section-label">CO-FOUNDER</span><h2>Nolann Petri</h2><p>ORVECT</p></div><div><span className="section-label">CO-FOUNDER</span><h2>Hesse Lesly</h2><p>Head of Technical Operations</p></div></div><div className="team-foundation"><h2>Current foundation</h2><p>A diagnostic prototype and 3 garages under beta agreements.</p><p className="key-line">Next milestone: repeatable value in the workshop.</p></div></>},
{id:"round",section:"10 / Pre-seed",title:"$350k to validate the workshop business",body:<div className="funding-layout"><div className="funding-ask"><strong>$350k</strong><p>Proposed pre-seed raise</p><span>$4.5M working pre-money<br/>~7.2% illustrative dilution</span></div><div><h2>Proposed use of funds</h2><ul className="allocation">{[[35,"Product + data"],[30,"GTM / workshop success"],[15,"Legal / data / compliance"],[10,"Infrastructure / security"],[10,"Reserve"]].map(([n,s])=><li key={s}><strong>{n}%</strong>{s}</li>)}</ul><p className="key-line">Fund the evidence for conversion, retention and repeatable onboarding.</p></div></div>,footer:"Fundraising proposal. Dilution before option-pool changes or other instruments. Budget and milestones require validation."},
{id:"closing",section:"ORVECT / Investor presentation",title:"Beyond the fault code.",cover:true,body:<><p className="closing-lead">3 garages. 12 diagnostics.<br/><span>The next milestone: repeatable workshop value.</span></p><div className="closing-contact"><strong>Nolann Petri</strong><a href="mailto:derka1385@yahoo.com">derka1385@yahoo.com</a></div></>},
{id:"system",section:"Appendix A1 / Architecture",title:"ORVECT controls the diagnostic workflow",body:<DiagramContainer><SystemFlowDiagram/></DiagramContainer>},
{id:"authority",section:"Appendix A2 / Control & safety",title:"The model never gets unconditional authority.",body:<><DiagramContainer><AuthorityGateDiagram/></DiagramContainer><div className="boundary"><b>The LLM cannot</b><span>Invent canonical sources</span><span>Rewrite DTC definitions</span><span>Decide safety</span><span>Turn field evidence into OEM truth</span></div></>,footer:"Backend owns provenance, canonical DTC integrity and safety decisions. Controls do not establish diagnostic accuracy."},
{id:"experience",section:"Appendix A3 / Experience admission",title:"Learn from validated outcomes. Never blind self-training.",body:<div className="two-col experience-layout"><ExperienceLoopDiagram/><div><h2>Admission rules</h2><List items={["Known outcome + canonical cause","Sufficient quality + consent","2+ independent workshops for cross-garage reuse","Confirmations > contradictions"]}/><p className="key-line">Field evidence never becomes OEM truth.</p></div></div>},
{id:"economics",section:"Appendix A4 / Cost per diagnostic",title:"An initial cost estimate, refined with usage",body:<div className="two-col cost-detail"><div><h2>Illustrative model cost</h2><p className="cost-formula">9,881 input × $0.15 / 1M<br/>+ 2,000 output × $0.60 / 1M</p><p className="cost-result">≈ $0.003</p><p>per diagnostic, for one model call</p><p className="muted">11,881 total tokens from one reported test. Input / output split assumed for this scenario.</p></div><div><h2>A more representative estimate</h2><p>More measured diagnostics through the ORVECT Engine help establish average cost across case types.</p><p className="key-line">Track complete cases, including research and retries.</p><p className="muted">Tavily, infrastructure, data licensing and support add to the model cost. Total cost per diagnostic remains to be measured.</p></div></div>,footer:<><a href="https://nebius.com/token-factory/prices" target="_blank" rel="noreferrer">Nebius Token Factory pricing</a> · gpt-oss-120b: $0.15 input / $0.60 output per million tokens. Scenario estimate, not a measured average.</>},
{id:"engineering",section:"Appendix A5 / Engineering evidence",title:"The technical foundation",body:<><div className="metrics"><Metric value="262" label="backend tests passed"/><Metric value="~$0.003" label="estimated model cost / diagnostic"/><Metric value="11,881" label="tokens on one test diagnostic"/></div><p className="proof-support">More measured diagnostics through the ORVECT Engine will refine the cost estimate across case types and research needs.</p></>,footer:<>Illustrative model cost: 9,881 input + 2,000 output tokens at $0.15 / $0.60 per million = $0.00268. Assumed token split, one call. Excludes Tavily, retries and operations. <a href="https://nebius.com/token-factory/prices" target="_blank" rel="noreferrer">Nebius pricing</a>.</>},
{id:"signature",section:"ORVECT / Discussion",title:"ORVECT",signature:true,body:<BrandSignature/>},
];
