"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Slide, type SlideDefinition } from "./primitives";
import "./presentation.css";
export function PresentationShell({slides}:{slides:SlideDefinition[]}){
 const [index,setIndex]=useState(0),[overview,setOverview]=useState(false),[fullscreen,setFullscreen]=useState(false),[message,setMessage]=useState("");
 const root=useRef<HTMLDivElement>(null),overviewButton=useRef<HTMLButtonElement>(null),grid=useRef<HTMLDivElement>(null);
 const go=useCallback((n:number)=>{const next=Math.max(0,Math.min(slides.length-1,n));setIndex(next);setOverview(false);const url=new URL(window.location.href);url.searchParams.set("slide",slides[next].id);window.history.replaceState(null,"",url);},[slides]);
 useEffect(()=>{const read=()=>{const value=new URL(window.location.href).searchParams.get("slide");const n=slides.findIndex(s=>s.id===value);setIndex(n<0?0:n);};read();window.addEventListener("popstate",read);return()=>window.removeEventListener("popstate",read);},[slides]);
 useEffect(()=>{if(overview){grid.current?.querySelector<HTMLButtonElement>('[aria-current="true"]')?.focus();}else{root.current?.querySelector<HTMLElement>("#slide-heading")?.focus({preventScroll:true});}},[index,overview]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.key==="Escape"){if(overview){setOverview(false);requestAnimationFrame(()=>overviewButton.current?.focus());}else if(document.fullscreenElement){void document.exitFullscreen();}return;}if(overview){if(e.key==="Tab"){const buttons=Array.from(grid.current?.querySelectorAll<HTMLButtonElement>("button")||[]);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&target===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&target===last){e.preventDefault();first?.focus();}}return;}if(target.closest("button,a,input,textarea,select,[contenteditable=true]")||e.altKey||e.ctrlKey||e.metaKey)return;if(["ArrowRight"," ","PageDown"].includes(e.key)){e.preventDefault();go(index+1);}if(["ArrowLeft","PageUp"].includes(e.key)){e.preventDefault();go(index-1);}if(e.key==="Home"){e.preventDefault();go(0);}if(e.key==="End"){e.preventDefault();go(slides.length-1);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[go,index,overview,slides.length]);
 useEffect(()=>{const change=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener("fullscreenchange",change);return()=>document.removeEventListener("fullscreenchange",change);},[]);
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.current?.requestFullscreen)await root.current.requestFullscreen();else setMessage("Fullscreen is unavailable in this browser. The presentation remains usable in this window.");}catch{setMessage("Fullscreen could not be opened. Use your browser’s fullscreen command.");}}
 return <div ref={root} className="presentation" lang="en"><div className="presentation-stage" inert={overview}><Slide key={slides[index].id} slide={slides[index]} index={index} total={slides.length}/></div><nav className="deck-controls" aria-label="Presentation controls" inert={overview}><span className="keyboard-hint">← → / Space</span><div className="slide-navigation"><button onClick={()=>go(index-1)} disabled={index===0} aria-label="Previous slide">←</button><span className="slide-count" aria-live="polite">{String(index+1).padStart(2,"0")} / {slides.length}</span><button onClick={()=>go(index+1)} disabled={index===slides.length-1} aria-label="Next slide">→</button></div><button ref={overviewButton} onClick={()=>setOverview(true)}>Overview</button><button onClick={()=>window.print()} className="print-button">Print / PDF</button><button onClick={toggleFullscreen}>{fullscreen?"Exit fullscreen":"Fullscreen"}</button></nav>{message&&<p className="deck-message" role="status">{message}<button onClick={()=>setMessage("")}>Dismiss</button></p>}{overview&&<div className="deck-overview" role="dialog" aria-modal="true" aria-labelledby="overview-title" ref={grid}><header><h2 id="overview-title">Investor presentation</h2><button onClick={()=>setOverview(false)}>Close overview</button></header><div className="overview-grid">{slides.map((slide,i)=><button key={slide.id} onClick={()=>go(i)} aria-current={index===i?"true":undefined}><small>{String(i+1).padStart(2,"0")} / {slide.section}</small><strong>{slide.title}</strong></button>)}</div></div>}<div className="print-deck">{slides.map((slide,i)=><Slide key={slide.id} slide={slide} index={i} total={slides.length} print/>)}</div></div>
}
