import type { ReactNode } from "react";
import { OrvectLogo } from "@/components/OrvectProduct";
export function Brand(){return <div className="deck-brand"><OrvectLogo/></div>}
export function SectionLabel({children}:{children:ReactNode}){return <p className="section-label">{children}</p>}
export function Metric({value,label}:{value:string;label:string}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}
export function SourceFooter({children}:{children:ReactNode}){return <footer className="source-footer">{children}</footer>}
export function DiagramContainer({children}:{children:ReactNode}){return <div className="diagram-container">{children}</div>}
export function SignalPath({index,total}:{index:number;total:number}){return <div className="signal-path" aria-label={`Slide ${index+1} of ${total}`}><svg viewBox="0 0 1000 12" preserveAspectRatio="none" aria-hidden="true"><path d="M0 6H1000"/><path className="signal-progress" d={`M0 6H${(index+1)/total*1000}`}/></svg></div>}
export type SlideDefinition={id:string;section:string;title:string;body:ReactNode;footer?:ReactNode;cover?:boolean;signature?:boolean};
// Opening signature reused from the landing page, held on its final frame.
export function BrandSignature(){return <div className="deck-signature" aria-hidden="true"><div className="deck-signature-lockup"><svg className="deck-signature-mark" viewBox="0 0 120 100" focusable="false"><path d="M8 76 29 24h19L27 76Z"/><path d="M41 76 70 4h19L60 76Z"/><path d="M74 76 95 24h19L93 76Z"/></svg><span className="deck-signature-name">ORVECT</span></div></div>}
export function Slide({slide,index,total,print=false}:{slide:SlideDefinition;index:number;total:number;print?:boolean}){if(slide.signature)return <article data-slide-id={slide.id} className="deck-slide signature-slide" aria-label={`${index+1}. ORVECT`} aria-roledescription="slide"><h1 className="sr-only" tabIndex={-1} id={print?undefined:"slide-heading"}>ORVECT</h1>{slide.body}</article>;return <article data-slide-id={slide.id} className={`deck-slide ${slide.cover?"cover":""}`} aria-label={`${index+1}. ${slide.title}`} aria-roledescription="slide"><header className="slide-top"><Brand/><SectionLabel>{slide.section}</SectionLabel></header><div className="slide-content"><h1 tabIndex={-1} id={print?undefined:"slide-heading"}>{slide.title}</h1>{slide.body}</div>{slide.footer&&<SourceFooter>{slide.footer}</SourceFooter>}<SignalPath index={index} total={total}/></article>}
